spring:
  application:
    name: rudy-chat
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: chat-group
      auto-offset-reset: latest
    producer:
      acks: 1
      retries: 3

server:
  port: 8081